services:
  - type: web
    name: my-project
    env: python
    runtime: python-3.11.9  # Specify Python version
    buildCommand: |
      apt-get update && apt-get install -y locales build-essential python3-dev
      echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
      locale-gen en_US.UTF-8
      update-locale LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8
      pip install -r requirements.txt
    startCommand: "gunicorn app:app"  # Adjust based on your app